apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatus-config-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatus-config-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gatus-config-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gatus-config-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gatus-config-controller.fullname" . }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --configmap-namespace={{ .Values.configMapNamespace }}
            - --configmap-name={{ .Values.configMapName }}
            - --config=/etc/gatus-config-controller/config.yaml
            {{- if .Values.logLevel }}
            - --zap-log-level={{ .Values.logLevel }}
            {{- end }}
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect=true
            - --leader-election-id={{ .Values.leaderElection.id }}
            - --leader-election-resource-lock={{ .Values.leaderElection.resourceLock }}
            {{- end }}
            {{- if .Values.watchHTTPRoutes }}
            - --watch-httproutes=true
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/gatus-config-controller
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "gatus-config-controller.fullname" . }}-config
