{{- if .Values.gatus.externalConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gatus.fullnameOverride | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatus-config-controller.labels" . | nindent 4 }}
{{- end }}
