apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatus-config-controller.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatus-config-controller.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
