apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.configMapNamespace }}
  labels:
    {{- include "gatus-config-controller.labels" . | nindent 4 }}
data:
  {{- if .Values.staticConfig }}
  static.yaml: |
    {{- toYaml .Values.staticConfig | nindent 4 }}
  {{- end }}
