apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gatus-config-controller.fullname" . }}
  namespace: {{ .Values.configMapNamespace }}
  labels:
    {{- include "gatus-config-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gatus-config-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gatus-config-controller.fullname" . }}
    namespace: {{ .Release.Namespace }}
